<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-EveRemote.Agent-d72befe7-d8d8-4024-a853-bf6c8d03065c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EveRemote.Core\EveRemote.Core.csproj" />
    <ProjectReference Include="..\EveRemote.Infrastructure\EveRemote.Infrastructure.csproj" />
    <ProjectReference Include="..\EveRemote.Protocol\EveRemote.Protocol.csproj" />
  </ItemGroup>
</Project>
